[project]
name = "ai-goal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fire>=0.7.0",
    "jupyter>=1.1.1",
    "llama-stack-client>=0.2.12",
    "requests>=2.32.4",
]
